import { Button } from "@/components/ui/button";
import { ArrowRight, Languages, Zap } from "lucide-react";

export default function WelcomePage() {
  const handleLogin = () => {
    window.location.href = "/api/login";
  };

  return (
    <div className="min-h-screen flex flex-col bg-background relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute top-[-20%] right-[-10%] w-[600px] h-[600px] bg-primary/5 rounded-full blur-[100px] pointer-events-none" />
      <div className="absolute bottom-[-20%] left-[-10%] w-[500px] h-[500px] bg-accent/5 rounded-full blur-[100px] pointer-events-none" />

      <nav className="p-6 md:p-10 flex justify-between items-center z-10">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-primary/10 rounded-xl">
            <Languages className="w-6 h-6 text-primary" />
          </div>
          <span className="font-display font-bold text-xl">NihongoAI</span>
        </div>
        <Button onClick={handleLogin} variant="outline" className="rounded-full px-6">
          Sign In
        </Button>
      </nav>

      <main className="flex-1 flex flex-col items-center justify-center text-center p-6 z-10 max-w-4xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-secondary text-secondary-foreground text-sm font-medium mb-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
          <Zap className="w-4 h-4 fill-accent text-accent" />
          <span>AI-Powered Language Learning</span>
        </div>

        <h1 className="text-5xl md:text-7xl font-display font-bold tracking-tight mb-6 bg-clip-text text-transparent bg-gradient-to-br from-foreground to-foreground/60 animate-in fade-in slide-in-from-bottom-6 duration-700 delay-100">
          Master Japanese <br />
          <span className="text-primary">One Chat at a Time</span>
        </h1>

        <p className="text-xl text-muted-foreground max-w-2xl mb-12 leading-relaxed animate-in fade-in slide-in-from-bottom-8 duration-700 delay-200">
          Engage in natural conversations. Get instant corrections, romaji transliteration, and daily personalized learning summaries generated by AI.
        </p>

        <div className="flex flex-col sm:flex-row gap-4 animate-in fade-in slide-in-from-bottom-10 duration-700 delay-300">
          <Button 
            size="lg" 
            onClick={handleLogin}
            className="rounded-full text-lg h-14 px-8 shadow-xl shadow-primary/20 hover:shadow-2xl hover:shadow-primary/30 transition-all hover:-translate-y-1"
          >
            Get Started Free <ArrowRight className="ml-2 w-5 h-5" />
          </Button>
        </div>

        {/* Feature Grid */}
        <div className="grid md:grid-cols-3 gap-8 mt-24 text-left w-full animate-in fade-in zoom-in-95 duration-1000 delay-500">
          {[
            {
              title: "Natural Conversation",
              desc: "Chat freely in English or Japanese. The AI understands context and nuance."
            },
            {
              title: "Instant Breakdown",
              desc: "Every message comes with Kanji, Romaji, and English translations."
            },
            {
              title: "Daily Summaries",
              desc: "Review your day with auto-generated summaries and vocabulary lists."
            }
          ].map((feature, i) => (
            <div key={i} className="p-6 rounded-3xl bg-card border border-border/50 shadow-sm hover:shadow-md transition-shadow">
              <h3 className="font-display font-bold text-lg mb-2">{feature.title}</h3>
              <p className="text-muted-foreground">{feature.desc}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className="p-6 text-center text-sm text-muted-foreground border-t border-border/40">
        © {new Date().getFullYear()} NihongoAI. All rights reserved.
      </footer>
    </div>
  );
}
